import "./globals.css";
import Navigation from "@/app/components/navigation";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "User Details Proyect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <div className="container mx-auto mt-20 p-4 border rounded-2xl justify-self-center">{children}</div>
      </body>
    </html>
  );
}
