version: '3'

services:
  app:
    image: node
    build: .
    volumes:
      - .:/usr/src/app
    container_name: docker-node
    restart: always
    ports:
      - 5000:3000
    command: node /usr/src/app/main.js
  db:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - '3606:3306'
    environment:      
      - MYSQL_ROOT_PASSWORD=test1